version: 1.0

system: "udit_rotary_v_b_1000"

ddim:
  v_prediction: true
  diffusers:
    num_train_timesteps: 1000
    beta_schedule: 'scaled_linear'
    beta_start: 0.00085
    beta_end: 0.012
    prediction_type: 'v_prediction'
    rescale_betas_zero_snr: true
    timestep_spacing: 'trailing'
    clip_sample: false

diffwrap:
  UDiT:  
    input_dim: 256
    output_dim: 128
    pos_method: 'none'
    pos_length: 500
    timbre_dim: 512
    hidden_size: 768
    depth: 12
    num_heads: 12